# Generated by Django 5.2.4 on 2025-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_downvotecounter_ipdownvote_userdownvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('employed_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        
    ]
