# Generated by Django 5.2.4 on 2025-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ipupvote_upvotecounter_userupvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
