# Generated by Django 5.2.4 on 2025-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='status',
        ),
        migrations.AddField(
            model_name='facility',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='occupied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
