# Generated by Django 5.2.4 on 2025-07-16 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_insuranceprovider_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceprovider',
            old_name='date_of_agreement',
            new_name='since',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='plans',
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='logo',
            field=models.URLField(default='https://via.placeholder.com/40?text=🏥'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='plan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
