# Generated by Django 5.2.4 on 2025-07-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_date_of_agreement_insuranceprovider_since_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='end_date',
            new_name='endYear',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='start_date',
            new_name='startYear',
        ),
        migrations.RemoveField(
            model_name='program',
            name='coordinator',
        ),
    ]
